### ISSUE TITLE
question about gene snps

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#119]
Hi!
I have a question about PRSice. I am using the software for pathway analysis (I am not using PRSet because I was having problems with the memory).
Anyway, since I am not using the p-value thresholding (just all the SNPs with P value greater than 0.05), how statistically it can affect my prediction (in compares with using value thresholding)?

**Comment by choishingwan** [comment]
So you are including all SNPs based on the assumption that all of them are
contributing? If that's the case, maybe you can only consider multiple
testing? Best if you have independent validation set where you can get the
out of sample prediction p-value / R2 though


Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by choishingwan** [comment]
Btw, are you still have difficulties in running the latest version of
PRSice? As in, can't seems to run it by directly pointing to the location
of it?
Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by sarasaezALS** [comment]
I included ALL the snps with a greater pvalue than 0.05 in the summary stats, (because I am doing pathway analysis and a few snps can not define a pathway), and I don't threshold them in the analysis.
I performed my analysis using a GWAS summary stats, and I have a target dataset and a replication dataset. ONLY FDR-corrected significant pathways with Beta greater Than 1 in the replication are considered as significant.
I think what it significant, it is robust. What I don't know is how to justify that I am not using p value thesholding and the prediction is still OK (as you may notice, I am a cell biologist trying to jump into the bioinformatics analysis)

**Comment by sarasaezALS** [comment]
> Btw, are you still have difficulties in running the latest version of PRSice? As in, can't seems to run it by directly pointing to the location of it? Dr Shing Wan Choi Postdoctoral Fellow Genetics and Genomic Sciences Icahn School of Medicine, Mount Sinai, NYC On Wed, Jun 12, 2019 at 3:00 PM Shing Wan Choi <choishingwan@gmail.com> wrote:
> […](#)

I tried several time and it did not work for me. SO, because of my analysis is done with PRSice PRSice 2.1.1, I continue with 2.1.1

**Comment by choishingwan** [comment]
I see. It is sad that you can't use the latest version, which should help
us to understand the memory error.

It is perfectly ok to not do p-value thresholding when doing a set base
analysis, in fact, that's the default for PRSet. The main problem with
thresholding is that, the best threshold for a set might include only one
single SNP in the extreme case, which makes it difficult to justify if the
signal is indeed the signal of the pathway. We think there might be better
way to do it, but haven't figure out a way yet.

The one downside of your analysis might be that the P-value obtained is
self-contained. That is, it is finding if the pathway PRS is associated
with the phenotype or not, instead of whether the pathway PRS is enriched
with signal related to the phenotype of interest, undermining the
usefulness of the p-value. You can construct 10,000 Null pathways with
similar number of SNPs (i.e. after clumping within genic region) then see
if your observed p-value is more significant.

One way that you can try is to rename the downloaded PRSice to a different
name, and see if by running with that will point you to the latest version.
e.g. assuming you are working in a new folder, assuming you are using
linux, type

mkdir PRSice
cd PRSice
wget
https://github.com/choishingwan/PRSice/releases/download/2.2.1/PRSice_linux.zip
unzip PRSice_linux.zip
mv PRSice_linux PRSice_v2.2.1

Then you can try PRSice_v2.2.1 -v
and see if you get the correct version number

Sam

**Comment by sarasaezALS** [comment]
OK Sam. Thanks for your help! really useful, as always. I am trying to wrap up this paper, with the self containing p-value. But I am planning to test PRSet (with competitive p value). I think is a concern than the referees could have.
I will let you know how it works once I try.

**Comment by sarasaezALS** [comment]
I am running again the last version. Finger crossed!
another question that I don't really know how to figure out is: I have a set of SNP per each pathway, how can I know the top snps that contribute the most to the significance of the PRS?

**Comment by choishingwan** [comment]
The SNPs that contribute the most will be the most significant SNP included in the PRS
