### ISSUE TITLE
what is the different between r2 threshold for clumping --clump-r2  and  --clump-p?

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#135]
Hi Sam,
what is the different between r2 threshold for clumping --clump-r2  and  --clump-p?

I select 1 for them because I want to be really restrictive. I found this can work better to  calculate PRS in gene sets. How  --clump-r2 = 1 can affect the results? Why 0.1 is the default?

**Comment by choishingwan** [comment]
`--clump-p` is a kind of filter. What it does it, for any SNP with p-value less than that number, they will be excluded from clumping, and thus exclude from the analysis. 

On the other hand `--clump-r2` is more important. It meant that for two SNPs with r2 higher than the specified threshold, one of them will be removed from the analysis (the one with less significant p-value). With a threshold of 1, you can have a higher R2, but the R2 is overfitted due to LD. As a result, we opt for a more conservative number of 0.1, which means SNP pairs with R2 > 0.1 will be clumped

**Comment by sarasaezALS** [comment]
OK, I see. 
It is ok to use --clump-r2?

**Comment by sarasaezALS** [comment]
OK, I see.
sorry, I meant: It is ok to use --clump-r2=1, since I am using a replication dataset?

**Comment by sarasaezALS** [comment]
Hi Sam,
what it is the default R2 for  --proxy?

**Comment by choishingwan** [comment]
No, unless you are certain the LD is not going to cause a problem, then it is best not to use `--clump-r2 1`.

As for proxy, we haven't test it's performance (whether this will improve the R2 prediction or not). So the default is to not use `--proxy`

**Comment by sarasaezALS** [comment]
I see..so, to select only independent SNPs within  the gene plus -/+ 15 kb (upstream/downstream of the gene), what should I choose?
the problem when I run this under default parameters is that I get a lot of SNPs outside of the gene (and for gene set is not helpful?

**Comment by choishingwan** [comment]
What do you mean by having SNPs outside of the gene? If you are using the defaults, then it should be something similar to 

`--clump-r2 0.1 --clump-kb 1mb --wind-5 0 --wind-3 0`
Which only consider SNPs within the gene to be part of the gene set

However, if you use `--proxy`, or use `--wind-5 15kb --wind-3 15kb`, then it is definitely possible for SNPs outside of the gene to be considered as part of the gene.

**Comment by sarasaezALS** [comment]
perfect!
thanks so much!
