### ISSUE TITLE
--wind-5

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#136]
I am using version 2.1.1,
it is possible to use --wind-5 or something similar?

**Comment by choishingwan** [comment]
I think `--wind-5` has already been implemented in 2.1.1 (but not in the Rscript). I will strongly suggest you to try and use 2.2.6, and maybe try and see why you cannot point to the latest executable? E.g. maybe instead of typing PRSice_linux XXXX, try ./PRSice_linux or even use the full path?

**Comment by sarasaezALS** [comment]
OK,
I am running something like this using v2.1.1, but it is not working:
Rscript /data/PRSice_linux-5/linux/PRSice.R --cov-file /data/eigenvec --out /data/VERSION2.6.6 -t /data/PHENO -b /data/Summary_Statistics --beta --snp SNP --A1 A1 --A2 A2 --stat b --se se --pvalue p --ld /data/workingData --print-snp --score std --perm 1000 --prsice /data/PRSice_linux-5/PRSice_linux -n 12 --binary-target T --maf 1E-2 --quantile 4 --prevalence 0.00005 --no-full --bar-levels 5E-2 --fastscore --gtf /data/Homo_sapiens.GRCh37.75.gtf --msigdb /data/cl.txt --multi-plot 10 --clump-r2 0.1 --wind-5 0 --wind-3 0

**Comment by choishingwan** [comment]
As mentioned in the previous message, I don't think `--wind-5` and `--wind-3` are implemented in the Rscript. You will have to run the analysis using only the executable. Though considering that you are using `--wind-5 0 --wind-3 0` you can safely ignore the parameter as the default is 0 anyway. 

Again, I still strongly recommend using 2.2.6 instead of 2.1.1, as I can't remember how many bugs i have fixed since then.

**Comment by sarasaezALS** [comment]
I am having some problems in the new version. Do you know why doesn’t it recognize —se (I use it for the se of the snps in the base file)

**Comment by choishingwan** [comment]
Good to know you can use the latest version. The reason why `--se` isn't recognize is because I removed this option. We never use the SE information in PRSice, and keeping large amount of stuff in PRSice makes it difficult for me to maintain it, especially now I need to work on other projects. With the latest version, you will need to remove `--se` from your parameters and also the following parameter have their name changed: 
`--maf-base` to `--base-maf`
`--info-base` to `--base-info`

So backward compatible change are
`--pheno-file` can now be specified as `--pheno`
`--cov-file` can now be specified as `--cov`

**Comment by sarasaezALS** [comment]
The new version 2.6.6 is running well! (no memory problems at all)
Thanks for your help!

I find a small number of variants in the pathways (using --clump-r2 0.1 and --clump-kb 10mb) is there any way to be less conservative in LD (to get more variants per pathway) while keeping the accuracy of the PRS calculation? Could I change --clump-r2 0.3 or --clump-kb 15kb?

**Comment by choishingwan** [comment]
I disabled the memory check on 2.2.6 as I found that the memory check isn't that accurate. 
You can be less conservative with LD but then we don't have a way to ensure the resulting PRS is correct. One way to increase the number of SNP is to use the `--wind-3` and `--wind-5` option, with the assumption that there are regulatory elements for your gene of interest upstream and downstream of the coding region. If I remember correctly, another program, MAGMA, recommend a window size of `--wind-5 3kb --wind-3 1.5kb`
