### ISSUE TITLE
PRSet column names shifted due to "Background" label in all.scores

### ISSUE THREAD

**Issue by ukuvainik** [choishingwan/PRSice#151]
Hi

I am using the PRSet with a MSigDB format SNP set. All seems to be working well, but the all.score file has an extra column "Background", which seems to shift the names of columns around. I am adding a picture, where you can see that the contents of columns are the same, but in all.score the column names are shifted compared to .best file. There is no pathway called "background".

While with p=1 i can safely use the .best file, it creates issues, if I have other p value levels, eg --bar-levels .01. Then the .best does not include only p=.01, but may also include p=1.

![prsset227_best_vs_all score](https://user-images.githubusercontent.com/6614391/64867206-9d338e80-d645-11e9-8707-602c1e450f5c.png)

[bmi_ukb18_cpdef_path.log](https://github.com/choishingwan/PRSice/files/3610299/bmi_ukb18_cpdef_path.log)

Best

Uku Vainik

**Comment by choishingwan** [comment]
I forgot to remove the background from the all.score file. Will remove it
from the next release.

As for the p-value, you are looking for the --no-full option, otherwise,
PRSice will always include the p-value of 1 as a default. (And we don't
recommend doing thresholding for PRSet due to difficulties in the
interpretation of results)

**Comment by choishingwan** [comment]
This problem is now fixed in 3dfe279655e50a88eda1e3ec1fbd6b975f43083b

**Comment by ukuvainik** [comment]
Thank you for the quick reply and fix! Could you please elaborate, what are the interpretation difficulties of thresholding?
