### ISSUE TITLE
.psam files

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#156]
Hi Sam,
I am trying to rung PRSice2 using WGS data and our binary files are in .psam format (from PLINK2). could they be used as a imput?

**Comment by choishingwan** [comment]
Unfortunately no, I simply don't have time to implement supports for more
than two format...   You will either need to change it into bgen or bed
format instead.


Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by sarasaezALS** [comment]
OK,
WILL DO! THANKS

**Comment by choishingwan** [comment]
I have recently (yesterday) received a bug report suggesting that the
logistic regression used by PRSice is somewhat problematic (since v 2.2.5).
Upon further investigation, that is indeed the case and the problem is
currently fixed (by using another less efficient algorithm). This might
solve your problem. Am now running tests on the latest code (which
constitute huge changes in the underlying structure of PRSice), and the
update should be release once I am confident that most of the functionality
of the new code base are working properly.

Thank you

Sam

**Comment by sarasaezALS** [comment]
Hi Sam,
Will the new version incorporate the p-competitive?
……………………………………
Sara Saez-Atienzar PhD
Postdoctoral Research Fellow
Neuromuscular Diseases Research Section
Laboratory of Neurogenetics, NIA, NIH
35 Convent Drive, Room 1A-108, Bethesda, MD 20892-3707

**Comment by choishingwan** [comment]
I won't delete that function.  So that should be there.

**Comment by sarasaezALS** [comment]
Perfect!!!!

……………………………………
Sara Saez-Atienzar PhD
Postdoctoral Research Fellow
Neuromuscular Diseases Research Section
Laboratory of Neurogenetics, NIA, NIH
35 Convent Drive, Room 1A-108, Bethesda, MD 20892-3707
