### ISSUE TITLE
Very sparse memory allocation

### ISSUE THREAD

**Issue by oyhel** [choishingwan/PRSice#165]
PRSice is only reserving a measly 72MB out of 128939MB during clumping. Nothing else is running on the server at the same time so it should be possible to allocate way more and speed things up. Something I can try to speed things up? I tried setting --memory 100Gb just to see if that would make any change, but none whatsoever. Any help appreciated.

`Loading Genotype info from target 
================================================== 

98110 people (0 male(s), 0 female(s)) observed 
98110 founder(s) included 

2260468 variant(s) not found in previous data 
557 ambiguous variant(s) excluded 
807837 variant(s) included 

Check Phenotype file: 
/myphenofile.txt 
Column Name of Sample ID: FID+IID 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
There are a total of 1 phenotype to process 

Start performing clumping 

128939 MB RAM detected; reserving 72 MB for clumping 

Allocated 72 MB successfully 

Clumping Progress: 1.43%`

**Comment by choishingwan** [comment]
Due to nature of clumping, assigning more memory will not help to speed things up (unless you use the `--enable-mmap` option and then assign enough memory to store the whole genotype file into the memory, then that might speed things up slightly). As a result of that, we just reserve the maximum amount of memory required for clumping. This is an expected behavior
