### ISSUE TITLE
Query with hard-thres

### ISSUE THREAD

**Issue by KatieSaxby1** [choishingwan/PRSice#170]
Hi Sam,

I have a query and hope you can help.  I am using PRSice2 for my MSc dissertation.  I have chosen to use a dosage-threshold of 0.9 and am not opting to hard call as I want to take the uncertainty of the imputed genotype into consideration.
The hard-thres default of 0.1 is being applied and I can't set this to 0.  If I'm not hard calling imputed genotypes, why is this value required please?  I've tried specifying different hard-thres values and it doesn't appear to affect the results so I think the parameter is redundant but I'd like to make sure for my write-up.  
Apologies in advance if I'm missing something obvious - if you can point me towards any literature to understand this, I'd really appreciate it.

Many thanks,
Katie

**Comment by choishingwan** [comment]
The `--hard-thres` is use for LD. We cannot calculate LD based on the dosage information. As a result of that, we will first convert the dosage into hard code when we calculate LD, that's why `--hard-thres` is applied. You can find more information [here](http://www.prsice.info/command_detail/#dosage)
