### ISSUE TITLE
--plot-set

### ISSUE THREAD

**Issue by carolstella** [choishingwan/PRSice#186]
Hi Sam, 

I am performing PRS analysis using PRset, but I have some problems with the plot. In addition to the multiplot I would like to get a barplot for each set. I am using the --plot-set <setname> command and I don't get any error, but there is no plot in the output (I tried either using multiplot or not, in case I use it I just get the multiplot) 

This are the commands that I am using:
Rscript ./Software/PRSice.R \
--dir . \
--prsice ./Software/PRSice_linux \
--base ./MDD_GWAS_chrpos.txt \
--target ./PGC_imput_QC_filtered \
--clump-kb 500 \
--clump-p 1.000000 \
--clump-r2 0.100000 \
--snp POS \
--A1 A1 \
--A2 A2 \
--stat OR \
--or \
--pvalue P \
--binary-target T \
--pheno ./pheno_SCZ \
--gtf ./Homo_sapiens.GRCh37.75.gtf \
--bed adult137Reg.bed,137svilReg.bed \
--maf 0.01 \
--multi-plot 10 \
--plot-set adult137Reg.bed,137svilReg.bed \
--set-perm 10000 \
--out MDDGWAS_on_SZTarget

As I downloaded the update PRSice to 2.2.10.b, I have no problems with permutation (but just in case I tried also with just 1000 permutations).

Thank you so much!

**Comment by choishingwan** [comment]
If I remember correctly, the plot-set option takes the name of the set,
instead of the region file. (So in theory, you do need to do this by hand
one at a time. The --plot parameter will be very useful). I can think about
implementing a feature to plot all sets but that'd be either after I have
completed the unit tests or when I am seriously procrastinating.
