### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mbxsrcha** [choishingwan/PRSice#203]
**Describe the bug**
When running PRSice-2.3.1.e, variants have been excluded from the analysis, reporting "1 variant(s) not found in previous data" although they are present in both base/target dataset. This issue was not identified in much earlier versions of PRSice-2 (2.1.3).

**Error Log**
[rs429358_issue.log](https://github.com/choishingwan/PRSice/files/4786095/rs429358_issue.log)

**To Reproduce**
[IGAP_rs429358.txt](https://github.com/choishingwan/PRSice/files/4786092/IGAP_rs429358.txt)

**Additional context**
I have identified the issue to be the P value calculated for this variant may not compute correctly and is removed. I have tried replacing the value with 0 and the variant is included again.

**Comment by choishingwan** [comment]
What's the original p-value? If it is invalid (e.g. NA, or string), then it
is normal for PRSice to remove it (as we can't get the correct p-value for
clumping)

Sam

**Comment by mbxsrcha** [comment]
The original p-value was 6.70e-536.

**Comment by choishingwan** [comment]
I'm surprised that such a small p-value can be printed. From my
understanding, most programming languages (C, C++, R, python) can only
represent a double value close to 1e-308. What happened here is that
because your p-value is so small, we can't convert it into a proper double
(it will be rounded to 0) and thus were removed. In previous versions, this
was just silently converted / dropped from the analysis (need to check). I
guess converting this to zero is alright in most use cases. May have a
think about how to handle this.
