### ISSUE TITLE
Output list of SNPs in optimized model

### ISSUE THREAD

**Issue by oyhel** [choishingwan/PRSice#224]
I could not find this implemented. Would it be possible for PRSice and PRSet to output the list of markers used in the optimized model?

**Comment by choishingwan** [comment]
Hi, you can use the --print-snmp option. That will output all the
post-clumped SNPs. You can then filter out the SNPs in the optimized model
based on their p-value. The reason for this round about way is so that we
can reduce the number of output files from PRSet which can sometime
generate up to a thousand files.

**Comment by oyhel** [comment]
Thank you very much for the swift reply and for a very well written software + documentation!
