### ISSUE TITLE
Possible to calculate PRS in a target set without available phenotype?

### ISSUE THREAD

**Issue by oyhel** [choishingwan/PRSice#225]
I have a situation where I have reference results from a GWAS, then a target set A with phenotype X available where I find the optimized model and spit out the SNPs used in the optimized model with --print-snp.

Now I have another target set B, without phenotype X available. In this set I merely want to calculate PRS for each sample in set B using the reference results and the SNPs found above using --print-snp.

I have looked through the available commands and I can not find any command specifying a list of input-snps to just get the PRS per individual in the target samples (without the phenotype). Am I missing some obvious way to do this or is it out of the scope of the software?

Thanks again for a very nice tool with great documentation!

**Comment by choishingwan** [comment]
I think what you might want is a combination of

--no-clump (avoid clumping)
--fastscore --bar-levels 1 --no-full (Use all the extracted SNPs for PRS
construction, or change the --bar-levels to the appropriate level if you
haven't pre-filtered the SNP list)
--no-regress (so that we will just generate the PRS)

**Comment by oyhel** [comment]
That makes sense, thank you for the quick reply!
