### ISSUE TITLE
Bonferroni correction

### ISSUE THREAD

**Issue by TeaByrd** [choishingwan/PRSice#240]
Hello,

I'm having basic question concerning the interpretation of the output.
Do I have to correct my best-fit PRS model for multiple testing (bonferroni correction) and if so, how? What is the number "n", that I use as a divider of the typical alpha 0.05. I know, that n is typically the number of tests. How many tests does PRsice apply when calculating the scores?

I'm running PRsice on a 106 samples target dataset with binary outcome.  

Best regards and thanks in advance, 
Thomas

**Comment by choishingwan** [comment]
You should usually correct for multiple-testing as we did do a lot of tests (one per threshold). But as our tests ain't completely independent (the PRS are cumulative by default), bonferronoi correction might be too stringent. 

What you can do is to do --perm, which is an inbuilt permutation algorithm to obtain an empirical p-value. You can have a go and see if that gives you sensible results. Though I will be careful with any interpretation based on this set of result due to the small sample size.

**Comment by TeaByrd** [comment]
> You should usually correct for multiple-testing as we did do a lot of tests (one per threshold). But as our tests ain't completely independent (the PRS are cumulative by default), bonferronoi correction might be too stringent.
> 
> What you can do is to do --perm, which is an inbuilt permutation algorithm to obtain an empirical p-value. You can have a go and see if that gives you sensible results. Though I will be careful with any interpretation based on this set of result due to the small sample size.

Yes. I've tried that. Empirical P-values are unfortunately not significant. Still, thanks for helping out.

Best,
Thomas
