### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iagojunger** [choishingwan/PRSice#248]
Dear PRSice developers

We are trying to solve some problems with specific summary statistics in PRSice. First of all, our summary doesn´t have a column “rs-id”, that identify SNPs. So I need to find a way to associate the other data in the head of the archive in order to solve the problem. We try so many ways, like defining --bp and --chr-id, but it still doesn’t identify the SNP.
After this, I tried to use:

“Rscript PRSice.R --dir . --prsice ./PRSice_linux --base 2020_Zhou_et_al_TSH_meta_HUNT-MGI-ThyroidOmics.txt --target add_AUE1_eur_nm-qc_info08_geno0.1_mind0.1_maf0.05_hwe1e-6.hg19.ch.fl.bg --thread 1 --stat Effect --binary-target T --bp Pos --chr Chr --A1 Allele1 --A2 Allele2 --out teste1summaryhormonios --pvalue P-value --beta --chr-id Chr --fastscore”

	With this command, PRSice starts reading the file, but it stops because it identifies some duplications of the SNPs. We copied the error below:

 “Error: A total of 23 duplicated SNP ID detected out of 19
       input SNPs! Valid SNP ID (post --extract /
       --exclude, non-duplicated SNPs) stored at
       teste1summaryhormonios.valid. You can avoid this
       error by using --extract
       teste1summaryhormonios.valid”

	After this error message, we applied the “.valid” command. However, PRSice removed all the SNPs instead of removing only the duplicates.

“Rscript PRSice.R --dir . --prsice ./PRSice_linux --base 2020_Zhou_et_al_TSH_meta_HUNT-MGI-ThyroidOmics.txt --target add_AUE1_eur_nm-qc_info08_geno0.1_mind0.1_maf0.05_hwe1e-6.hg19.ch.fl.bg --thread 1 --stat Effect --binary-target T --bp Pos --chr Chr --A1 Allele1 --A2 Allele2 --out teste1summaryhormonios --pvalue P-value --beta --chr-id Chr --fastscore --extract teste1summaryhormonios.valid”

 “Error: No valid variant remaining”

	In addition, we have realized other tests trying to redefine --chr-id but it still doesn´t work. In conclusion, how can we solve this problem of defining SNPs based on --bp and --chr-id?

**Comment by choishingwan** [comment]
Yes, I kinda recognized this (and I am currently trying to solve this).

If I remember correctly, the main problem is that the valid file contains
the rs id, instead of the chr-id, so that when doing selection, the none of
the SNPs were found in the summary stat (which only contains the chr-id).

So for now, chr-id doesn't work well when there are duplicates. If I
remember correctly, the way I work around this in my previous analysis was
that I post process the valid file my matching to the bim and get the
chr-id instead. So if I made chr-id of CHR:BP, then I did

awk 'NR==FNR {a[$1]=$1} NR != FNR && $2 in a { print $1":"$4}'
teste1summaryhormonios.valid
add_AUE1_eur_nm-qc_info08_geno0.1_mind0.1_maf0.05_hwe1e-6.hg19.ch.fl.bg.bim
> out

something along that line.

I am currently working on something to solve this, but I don't expect to
finish it before early next year. So this might be the way to go forward
for now.

Sam
