### ISSUE TITLE
[BUG] --perm is not performed

### ISSUE THREAD

**Issue by JoniColeman** [choishingwan/PRSice#278]
When using PRSice 2.3.3, setting --perm 10000 is ignored, and no permutation is run (for binary targets). The analysis appears to otherwise complete as expected.

**Comment by choishingwan** [comment]
Thanks @JoniColeman , will look into it

**Comment by choishingwan** [comment]
Now that I check, I have fixed this back in April, but forgot to compile the release (same for the prevalence issue). Will try to update it today. 

Side note: The R2 calculation with covariate is now updated to be more accurate. Instead of Full.R2 - Null.R2, it is now 

1 - (1-Full.R2) / (1- Null.R2). Apparently, this is more robust. Will update the documentation when I have time.

**Comment by JoniColeman** [comment]
Sorry, Sam - this does not seem to be fixed by 2.3.5. (#277 is fixed though)

**Comment by choishingwan** [comment]
Hi Joni, do you mind sending me the log? My test does show that perm is run (result contain an empirical-p value column), though the end message does still asked for --perm.

**Comment by JoniColeman** [comment]
Ignore this - I was looking at the wrong file...
