### ISSUE TITLE
No error but getting no results

### ISSUE THREAD

**Issue by sakuramodokich** [choishingwan/PRSice#331]
Hi, 
[PRSice.log](https://github.com/choishingwan/PRSice/files/12062202/PRSice.log)
I ran PRSice but the barplot show zero p-values and grey bars, and no significant results were generated. Attached is the log file.

**Comment by sakuramodokich** [comment]
![PRSice_BARPLOT_2023-07-15](https://github.com/choishingwan/PRSice/assets/109240615/682bfd97-7118-4bc8-a5cb-f609d2edae28)
![PRSice_HIGH-RES_PLOT_2023-07-15](https://github.com/choishingwan/PRSice/assets/109240615/d3f28f58-e0bc-4070-a946-1b12ccdd7e12)

**Comment by sakuramodokich** [comment]
@choishingwan Is this ordinary? Please kindly advise on a solution.

**Comment by JoniColeman** [comment]
If you check the .prsice file, I imagine you will find that the polygenic risk scores are all extremely significantly associated with the phenotype, such that all the p values are lower than machine tolerance (and hence set to 0). 

I suspect this is due to overfitting – is there sample overlap between your target cohort and your base GWAS?
