### ISSUE TITLE
Clarification on clumping

### ISSUE THREAD

**Issue by privefl** [choishingwan/PRSice#35]
I have 2 quick questions on the clumping algorithm you use:
1. Do you use all the target dataset or only the controls of this target dataset (when there is a binary phenotype, of course)?
2. How do you estimate LD: with the pearson correlation or some haplotypic estimate (like PLINK)?

**Comment by choishingwan** [comment]
1. We use all the target dataset after exclusion / inclusion. Therefore, both case and controls are included in the LD calculation. You can exclude the case from the LD calculation by using the --ld option.

2. Our LD calculation algorithm is exactly the same as PLINK. We have directly used the coding from PLINK 2 to perform the clumping (with some twist so that we can handle SNPs from different pathways etc)

**Comment by privefl** [comment]
Thanks for your fast answer.
