### ISSUE TITLE
LD clumping and risk-increasing alleles

### ISSUE THREAD

**Issue by JosephD12** [choishingwan/PRSice#50]
Hi, I have a couple of general questions to the methods I hope you can help me with.

1) In the Detailed Guide, it says "When your target sample is small (e.g. < 500 samples), you might want to use an external reference panel to improve the LD estimation for clumping.". I have around 500 samples in my target sample, but if I were to have a suitable reference panel for my work it would probably be the 1000 Genomes Phase 1 version 3 EUR samples, which have only 379 samples. Would you suggest I use a reference panel which is smaller than my target sample? 
2) I'm new to PRS but the research unit I work in haven't used PRSice before and their older method always counted risk-increasing alleles- i.e. exhange A1 and A2 and invert the effect in the discovery sample in order to only sum risk-increasing alleles (output scores are >=0). It would help my understanding if I knew the reasoning behind PRSice not only counting risk-increasing alleles (the toy data output has PRS both above and below 0)? Or is there a command option for this I have overlooked? 

Thanks in advance!
Joseph

**Comment by choishingwan** [comment]
1. The more sample, the better. We recommended 500 samples because that is roughly the amount of samples in 1000 Genome. For EUR Phase 3 samples, there are a total of 670 samples. 

2. Because risk isn't one directional. There can also be protective alleles and by only considering the increasing alleles, you are missing out on those and can potentially bias your results.

**Comment by JosephD12** [comment]
Thank you for your answers, much appreciated!!
