### ISSUE TITLE
Allow sex chromosome in calculation

### ISSUE THREAD

**Issue by choishingwan** [choishingwan/PRSice#65]
Currently PRSice simply remove all Sex chromosome in its calculation. Might consider adding support later on (e.g. support for non-diploid chromosome)

**Comment by BioMatt** [comment]
Has there been a solution to allow ambiguous or sex chromosomes? As it is, I cannot get PRSice to work with non-human association data.

**Comment by choishingwan** [comment]
--keep-ambig allows you to keep ambiguous SNPs

Unfortunately, we don't support sex chromosome yet. I just don't have the
time to develop that

For non-human association data, you might want to use --num-auto to
increase the number of autosome to make it work. Though do make sure that
the chromosome of your organism is diploid, as I don't think I have
implemented method for non-diploid organism.

Sam

**Comment by mdw38** [comment]
> For non-human association data, you might want to use --num-auto to increase the number of autosome to make it work. 

I've run into an issue for cat genomes, which are alphanumeric A1, A2, B1, B2, etc.  
PRSice-2 excludes all variants saying "excluded as they are on unknown/sex chromosome"
I think this is because PRSice-2 cannot handle alphanumeric chromsome formats.
Using --keep-abmig and increasing --num-auto have no effect, and all variants are still excluded.

I'm going to try reformatting the target and base data with dummy numeric chromosomes, but are there any PRSice-2 options for it to handle alphanumeric chromosome formats?
