### ISSUE TITLE
All *.all.scores files are identical

### ISSUE THREAD

**Issue by wiedenhoeft** [choishingwan/PRSice#71]
I ran PRSice 2.1.3.beta on four quantitative phenotype columns, which I confirmed are all different. However, using the --all-score option, the resulting *.all.score files are byte-by-byte identical (according to fdupes). While its possible that the values are similar for strongly related phenotypes, the fact that they don't differ by a single digit makes me think that this is a bug.

**Comment by choishingwan** [comment]
Could you please send me the full log file?

**Comment by choishingwan** [comment]
Oh, wait, I should've read more carefully. 

You are using different phenotype for the same samples, right? In that case, the all score should be the same because

1. You have the same base file, therefore the input effect sizes are the same
2. You have the same genotype, as you are only changing the phenotype, your PRS should be the same

While your *.all.score files should be the same ( I should've only generated one), your .prsice and .summary file should differ.

**Comment by wiedenhoeft** [comment]
Oh yes, my bad, these are the actual PRS, I was confusing those with the *.prsice files. But I agree, it is confusing to have one for each phenotype.
