### ISSUE TITLE
Cannot use "--missing NO_MEAN_IMPUTATION"

### ISSUE THREAD

**Issue by buddej** [choishingwan/PRSice#81]
When trying to use the option `--missing no_mean_imputation` I receive the error:
```
Error: Unrecognized Missing handling method:
       NO_MEAN_IMPUTATION!
```
Both [the documentation](https://github.com/choishingwan/PRSice/blob/5276be2302ab0af91618747a33fc63b163f71308/docs/pthresholding.md) and [the option parsing code](https://github.com/choishingwan/PRSice/blob/ca28c81f23b6c7335ff4975bffb032648ca95f32/inc/commander.hpp#L154) seem to be expecting NO_MEAN_IMPUTATION.

However, the [class](https://github.com/choishingwan/PRSice/blob/ca28c81f23b6c7335ff4975bffb032648ca95f32/inc/storage.hpp#L147) contains the following values:
```
enum class MISSING_SCORE
{
    MEAN_IMPUTE,
    SET_ZERO,
    CENTER
};
```

The program runs if I use the option `--missing SET_ZERO`, but based on commander.hpp, it looks like since the string doesn't match, MISSING_SCORE::MEAN_IMPUTE will be returned, and PRSice will run in that mode.

**Comment by choishingwan** [comment]
Ar, my bad, I haven't updated the documentation accordingly. 

The accepted options are:
1. MEAN_IMPUTE
2. SET_ZERO
3. CENTER

and instead of doing string matching, I did a fuzzy matching which essentially only match the first character of the command, i.e. S, M and C. 

In theory --missing SET_ZERO should work. I will now try to update the document and also make the log more clear as to what we used (our log should show what's in effect for the --missing parameter)

**Comment by choishingwan** [comment]
Have now updated the document. Hope that clear things out

**Comment by udube** [comment]
When I use the option --missing SET_ZERO, I don't see a line if the log for --missing. I do see it for --score (--score SET_MISSING). Is that the expected output?

**Comment by choishingwan** [comment]
That's a bug in the log output. I have accidentally set the --missing to --score. Will update accordingly
