### ISSUE TITLE
Only one column detected

### ISSUE THREAD

**Issue by wiedenhoeft** [choishingwan/PRSice#84]
I'm getting the message "Only one column detected, will assume only SNP ID is 
provided". What is this referring to, and what would be the effect of this?

**Comment by choishingwan** [comment]
When we do SNP --extract / --exclusion, PRSice allow multiple types of input. PRSice will go through the following sequence:

1. Find if there's any column with column header name SNP, RS, RS.ID, RSID or RS_ID, if there is such column, use it as the SNP ID for extraction or exclusion
2. If no header is identified, check the number of column in the file.
    a. If there are 6 columns, we assume this is a bim file where the second column contain the SNP ID
    b. Otherwise,  assume the first column contain the SNP ID

All this does is to allow PRSice to select the column with the SNP ID information to perform the extraction and exclusion. If you only have one column in your exclusion or exclusion list, it is likely that should be the SNP ID and PRSice should be correct. PRSice still give this information just in case our assumption is wrong so that user can troubleshoot the problem.

Hope that answer your question (and I should really update the documentation once I've got time...)

**Comment by wiedenhoeft** [comment]
Yes, that was very helpful. Thanks! :-)
